stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
    outs:
      - data/raw/
  
  data_preprocessing:
    cmd: python src/components/data_preprocessing.py
    deps:
      - src/components/data_preprocessing.py
      - data/raw/
      - src/utils/preprocessing.py
    outs:
      - data/processed/

  model_training:
    cmd: python src/pipeline/training_pipeline.py
    deps:
      - src/pipeline/training_pipeline.py
      - data/processed/
      - src/utils/preprocessing.py
    outs:
      - artifacts/